### ISSUE TITLE
thinking forest biome has a jungle tag, causes cross-mod issues with mods that add structures to jungles

### ISSUE THREAD

**Issue by f-raZ0R** [Heart-of-the-Machine/heart-of-the-machine#27]
![2020-10-29_07 31 36](https://user-images.githubusercontent.com/30442287/97563065-ef09b600-19b8-11eb-9856-012373400121.png)
this image speaks for itself. Because the forest has the jungle tag, mods like repurposed structures that don't care about the dimension, only the biome type, can put structures that are meant to only be in overworld jungles, into thinking forests. Maybe... don't use the jungle tag?

**Comment by Kneelawk** [comment]
Yeah. This is going to be fixed when i get to it. The Thinking Forest was originally intended to resemble a jungle, but that has changed.

**Comment by Kneelawk** [comment]
Turns out this was also causing a really nasty crash with AE2. This should be fixed by 617c8e1b887551a032aa84bd36ec7bfa0a9ced63.
