### ISSUE TITLE
[request] Make feature generation settings configurable

### ISSUE THREAD

**Issue by Danklor** [Heart-of-the-Machine/heart-of-the-machine#5]
In hotm 0.1.3 the NECTERE_PORTAL feature generates everywhere except a hardcoded list of biome categories.

Please add the ability to allow / deny hotm features for biome and/or biome category lists in the config file.

I'd like to exclude some other biomes such as a modded void dimension that currently has unintended floating Nectere portals scattered about.

**Comment by Kneelawk** [comment]
I've begun working on this in 8056e26. This commit allows users to enable and disable specific biomes for Nectere portals to generate in using a file `hotm.yml` in the `config` folder. Hopefully this should do the trick.

Allowing users to enable and disable Nectere portal generation in biomes has brought up some other issues which I am working on next.
